# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  print_pipeline_id:
    description: "this command prints a pipelineid to the console"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:
  new_job:
     docker:
       - image: cimg/base:stable
     steps:
       - print_pipleline_id
workflows:
  save_hello_world_output_workflow:
    jobs:
      - new_job:

